In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('gurgaon_properties.csv')

In [3]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,1.07,6524.0,1640.0,Super Built up area 1640(152.36 sq.m.),2,2,3,pooja room,"245, Sector 85 Gurgaon, Gurgaon, Haryana",21.0,South,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",This lovely 2 bhk apartment/flat in sector 85 ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,2.78,11346.0,2450.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,3,3,"study room,servant room","Sector 113 Gurgaon , Gurgaon, Haryana",3.0,North,0 to 1 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,"['2 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...",NaN
2,3 BHK Flat in Sector 76 Gurgaon,flat,whiteland the aspen,3.50,11917.0,2937.0,Built Up area: 2937 (272.86 sq.m.)Carpet area:...,3,4,3,not available,"Sector 76, Delhi Gurgaon Expressway, Sector 76...",8.0,NaN,undefined,"['S.R.S. Hospital and Critical Care Unit', 'Pe...",Multistorey apartment is available for sale. I...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3,3 BHK Flat in Sector 43 Gurgaon,flat,sanskriti apartments,2.50,13513.0,1850.0,Super Built up area 1850(171.87 sq.m.),3,2,3,study room,"B-505, Sector 43 Gurgaon, Gurgaon, Haryana",5.0,East,10+ Year Old,"['Huda city centre metro station', 'Hanuman Ma...",Residential apartment for sell.Located in sect...,"['1 Wardrobe', '1 Modular Kitchen', 'No AC', '...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,1.42,8998.0,1578.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,"Sector 69 Gurgaon, Gurgaon, Haryana",8.0,East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",A well maintained 3 bhk flat available on sale...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."

In [4]:
#shape
df.shape

(3961, 20)

In [5]:
#info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [6]:
#check duplicates
df.duplicated().sum()

np.int64(0)

In [7]:
#check missing
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [8]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [11]:
df.sample(5)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3819,2 BHK Flat in Sohna,flat,gls arawali homes,Sohna,0.30,6243.0,481.0,Super Built up area 567(52.68 sq.m.)Carpet are...,2,2,...,not available,"405, Sohna, Gurgaon, Haryana",4.0,East,1 to 5 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...",Check out this 2 bhk apartment for sale in gls...,"['1 Water Purifier', '3 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of..."
3596,2 Bedroom House for sale in Sector 39 Gurgaon,house,independent,Sector 39,1.70,17980.0,945.0,Plot area 900(83.61 sq.m.),2,2,...,"store room,servant room","000, Sector 39 Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'State bank of india AT...","Huda allotted sector plots, very nice area, be...","['3 Wardrobe', '3 Fan', '5 Light', 'No AC', 'N...","['Water Storage', 'No open drainage around', '...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1326,2 Bedroom House for sale in Sector 36 Sohna,house,independent,Sector 36 Sohna,0.66,7168.0,921.0,Built Up area: 823 (76.46 sq.m.),2,2,...,not available,"Signature Global Park Iii, Sector 36 Sohna, Gu...",4.0,NaN,0 to 1 Year Old,NaN,Corner unit & 2 bhk independent floor for sale...,NaN,NaN,NaN
2410,2 BHK Flat in Sector 36 Gurgaon,flat,signature global infinity mall,Sector 36,0.41,6269.0,654.0,Built Up area: 654 (60.76 sq.m.),2,2,...,not available,"Sohna Sector 36, Sector 36 Gurgaon, Gurgaon, H...",3.0,NaN,undefined,NaN,Best in class property available at sector 36 ...,NaN,NaN,NaN
2561,2 BHK Flat in Sector 82 Gurgaon,flat,vatika the seven lamps,Sector 82,0.89,8850.0,1006.0,Super Built up area 1428.08(132.67 sq.m.)Carpe...,2,2,...,study room,"Sector 82 Gurgaon, Gurgaon, Haryana",14.0,East,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...","Brokers excuse, 2bhk+study, 1430 sq. Ft., east...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."

In [12]:
df['sector'] = df['sector'].str.lower()

In [13]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,sector 85,1.07,6524.0,1640.0,Super Built up area 1640(152.36 sq.m.),2,2,...,pooja room,"245, Sector 85 Gurgaon, Gurgaon, Haryana",21.0,South,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",This lovely 2 bhk apartment/flat in sector 85 ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,sector 113,2.78,11346.0,2450.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,3,...,"study room,servant room","Sector 113 Gurgaon , Gurgaon, Haryana",3.0,North,0 to 1 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,"['2 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...",NaN
2,3 BHK Flat in Sector 76 Gurgaon,flat,whiteland the aspen,sector 76,3.50,11917.0,2937.0,Built Up area: 2937 (272.86 sq.m.)Carpet area:...,3,4,...,not available,"Sector 76, Delhi Gurgaon Expressway, Sector 76...",8.0,NaN,undefined,"['S.R.S. Hospital and Critical Care Unit', 'Pe...",Multistorey apartment is available for sale. I...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3,3 BHK Flat in Sector 43 Gurgaon,flat,sanskriti apartments,sector 43,2.50,13513.0,1850.0,Super Built up area 1850(171.87 sq.m.),3,2,...,study room,"B-505, Sector 43 Gurgaon, Gurgaon, Haryana",5.0,East,10+ Year Old,"['Huda city centre metro station', 'Hanuman Ma...",Residential apartment for sell.Located in sect...,"['1 Wardrobe', '1 Modular Kitchen', 'No AC', '...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,sector 69,1.42,8998.0,1578.0,Super Built up area 1578(146.6 sq.m.),3,3,...,pooja room,"Sector 69 Gurgaon, Gurgaon, Haryana",8.0,East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",A well maintained 3 bhk flat available on sale...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."

In [14]:
df['sector'].value_counts()

sector
sohna                         163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
                             ...
rajiv colony                    1
huda saraswati vihar            1
garauli kalan                   1
jacobpura near sadar bazar      1
mahavir pura                    1
Name: count, Length: 301, dtype: int64

In [15]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [16]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [17]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,sector 85,1.07,6524.0,1640.0,Super Built up area 1640(152.36 sq.m.),2,2,...,pooja room,"245, Sector 85 Gurgaon, Gurgaon, Haryana",21.0,South,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",This lovely 2 bhk apartment/flat in sector 85 ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,sector 113,2.78,11346.0,2450.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,3,...,"study room,servant room","Sector 113 Gurgaon , Gurgaon, Haryana",3.0,North,0 to 1 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,"['2 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...",NaN
2,3 BHK Flat in Sector 76 Gurgaon,flat,whiteland the aspen,sector 76,3.50,11917.0,2937.0,Built Up area: 2937 (272.86 sq.m.)Carpet area:...,3,4,...,not available,"Sector 76, Delhi Gurgaon Expressway, Sector 76...",8.0,NaN,undefined,"['S.R.S. Hospital and Critical Care Unit', 'Pe...",Multistorey apartment is available for sale. I...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3,3 BHK Flat in Sector 43 Gurgaon,flat,sanskriti apartments,sector 43,2.50,13513.0,1850.0,Super Built up area 1850(171.87 sq.m.),3,2,...,study room,"B-505, Sector 43 Gurgaon, Gurgaon, Haryana",5.0,East,10+ Year Old,"['Huda city centre metro station', 'Hanuman Ma...",Residential apartment for sell.Located in sect...,"['1 Wardrobe', '1 Modular Kitchen', 'No AC', '...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,sector 69,1.42,8998.0,1578.0,Super Built up area 1578(146.6 sq.m.),3,3,...,pooja room,"Sector 69 Gurgaon, Gurgaon, Haryana",8.0,East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",A well maintained 3 bhk flat available on sale...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."

In [19]:
df['sector'].value_counts()

sector
sohna road     163
sector 102     113
sector 85      110
sector 92      104
sector 69       94
              ...
sector 17b       3
patel nagar      3
sector 88b       3
sector 15        3
sector 73        3
Name: count, Length: 131, dtype: int64

In [18]:
df.shape

(3803, 21)

In [20]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [21]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1551,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,...,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2031,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,...,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2133,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,...,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3356,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,...,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [22]:
df.loc[1551,'sector'] = 'sector 37'
df.loc[2031,'sector'] = 'sector 90'
df.loc[2133,'sector'] = 'sector 92'
df.loc[3356,'sector'] = 'sector 76'

In [23]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
32,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,...,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
1182,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,...,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
2299,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,...,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3043,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,...,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3533,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,...,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [24]:
df.loc[[32,1182,2299,3043,3533],'sector'] = 'sector 110'

In [25]:
df.shape

(3803, 21)

In [26]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,sector 85,1.07,6524.0,1640.0,Super Built up area 1640(152.36 sq.m.),2,2,...,pooja room,"245, Sector 85 Gurgaon, Gurgaon, Haryana",21.0,South,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",This lovely 2 bhk apartment/flat in sector 85 ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,sector 113,2.78,11346.0,2450.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,3,...,"study room,servant room","Sector 113 Gurgaon , Gurgaon, Haryana",3.0,North,0 to 1 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,"['2 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...",NaN
2,3 BHK Flat in Sector 76 Gurgaon,flat,whiteland the aspen,sector 76,3.50,11917.0,2937.0,Built Up area: 2937 (272.86 sq.m.)Carpet area:...,3,4,...,not available,"Sector 76, Delhi Gurgaon Expressway, Sector 76...",8.0,NaN,undefined,"['S.R.S. Hospital and Critical Care Unit', 'Pe...",Multistorey apartment is available for sale. I...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3,3 BHK Flat in Sector 43 Gurgaon,flat,sanskriti apartments,sector 43,2.50,13513.0,1850.0,Super Built up area 1850(171.87 sq.m.),3,2,...,study room,"B-505, Sector 43 Gurgaon, Gurgaon, Haryana",5.0,East,10+ Year Old,"['Huda city centre metro station', 'Hanuman Ma...",Residential apartment for sell.Located in sect...,"['1 Wardrobe', '1 Modular Kitchen', 'No AC', '...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,sector 69,1.42,8998.0,1578.0,Super Built up area 1578(146.6 sq.m.),3,3,...,pooja room,"Sector 69 Gurgaon, Gurgaon, Haryana",8.0,East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",A well maintained 3 bhk flat available on sale...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."

In [27]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)